### ISSUE TITLE
SAVE OPEN BUTTON

### ISSUE THREAD

**Issue by robertofazio** [robertofazio/elementMap#14]
TASTO SAVE E OPEN non salvano bene tutte le caratteristiche

**Comment by robertofazio** [comment]
elenco delle cose che non salva (wip) : 
1. main opacity

**Comment by mauro-ferrario** [comment]
Non ho ricaricato il codice nuovo, ma solo un nota che magari può servire: 
togliendo i commenti alla riga 397 e 405 di elementMixer.cpp, vengono salvati e caricati i settaggi del mixer (compresa l'opacità). Solo che così quando si carica un progetto, la seconda finestra passa in automatico in fullscreen e se si abbassa l'opacità dietro si vede nero e non più i "quadretti a scacchi" che indicano la trasparenza.
