### ISSUE TITLE
Auto "RESET GRID" on change input mode

### ISSUE THREAD

**Issue by mauro-ferrario** [robertofazio/elementMap#47]
Ho fatto questa modifica. Se ho capito bene, ora dovrebbe funzionare, ma con un "escamotage" non proprio dei migliori. Comunque sono 5 righe di codice, quindi non ho incasinato nulla.

**Comment by robertofazio** [comment]
si è sputtantato il warp (!) ora i contenuti non si adattano correttamente e il quad warp non funziona più correttamente (!) what's happened ? help

**Comment by mauro-ferrario** [comment]
Ho ricaricato ora la versione di Cinzio. Domani parlo con Cinzio riguardo a delle cose che mi sembrava di aver capito, ma probabilmente ho fatto confusione sul resto.... o forse su tutto.

**Comment by ofCinzio** [comment]
Cinzio conferma che l'escamotage funziona, e che aggiungendo una condizione per quando si carica un nuovo file si sistema tutto!

**Comment by robertofazio** [comment]
Se aprì una configurazione salvata invece? Devi sempre cliccare su un tasto per ovviare?

**Comment by ofCinzio** [comment]
ora l'errore c'è proprio perché apre in automatico l'ultima cosa salvata. è risolto sul cambio di tipi di input, adesso estendiamo alle altre azioni!

**Comment by ofCinzio** [comment]
lo consideriamo un sotto-bug del "reset grid", perciò: fixed.
