### ISSUE TITLE
TRASPARENZA LIVELLO

### ISSUE THREAD

**Issue by robertofazio** [robertofazio/elementMap#5]
il livello video non ha trasparenza esterna -> impostare BLENDING MODE = ADD

**Comment by robertofazio** [comment]
Nessun element mantiene il livello trasparenza, di default caricando un video animation con canale alhpa ( in DropBox c'è TEST004 ) dovrebbe di default essere visto correttamente. Qui qualche link di rifeferimento :+1: 

http://forum.openframeworks.cc/index.php/topic,1499.0.html
http://forum.openframeworks.cc/index.php/topic,10311.0.html
http://forum.openframeworks.cc/index.php/topic,364.0.html
http://forum.openframeworks.cc/index.php/topic,3223.0.html

**Comment by ofCinzio** [comment]
solved upgrading oF to v0073. if errors still exist, add "Accelerate framework" to project
