### ISSUE TITLE
RESET GRID

### ISSUE THREAD

**Issue by robertofazio** [robertofazio/elementMap#7]
RESET GRID : per visualizzare correttamente un file caricato la sequenza è: LOAD -> INPUT TYPE -> RESET GRID

inoltre deve funzionare solo quando è attivato FINE WARPING altrimenti non ha effetto

**Comment by mauro-ferrario** [comment]
Non sono sicuro di aver capito le modifiche dato che sono rientrato ora dopo molto tempo.
Comunque se ho capito bene, ora ho fatto in modo che il RESED GRID funziona solo se il FINE WARPING è attivo

**Comment by ofCinzio** [comment]
Sistemato by Mauro&Cinzio collaboration. o almeno così sembra! :)
