### ISSUE TITLE
FINE WARPING

### ISSUE THREAD

**Issue by robertofazio** [robertofazio/elementMap#8]
FINE WARPING : aumentando e diminuendo la risoluzione della griglia dsi modifica la dimensione del contenuto

**Comment by robertofazio** [comment]
Ho notato che fino alla risoluzione 6x6 la texture sotto non si muove.
Alzando la risoluzione inizia a spostarsi (!)

**Comment by ofCinzio** [comment]
credo che siano le approssimazioni che fa nella divisione della texture in quadrati; bisogna bloccare la precisione alla frazione di pixel.
